/*
 * This source file was generated by the Gradle 'init' task
 */
package org.jetbrains.hackathon2024

import org.gradle.api.Project
import org.gradle.api.Plugin

class KapiFencePlugin : Plugin<Project> {
    override fun apply(project: Project) {
        with(project) {
            configureDeprecationsAttribute()
            registerDeprecationsTransform()
        }
    }
}

